joy_teleop:
  autorepeat_rate: 0.05

teleop:
  move:
    type: topic
    message_type: geometry_msgs/Twist
    topic_name: cmd_vel
    axis_mappings:
      -
        axis: 1
        target: linear.x
        scale: 1.0
      -
        axis: 3
        target: angular.z
        scale: 1.0

  head_down:
    type: action
    action_name: /head_controller/increment
    action_goal:
      increment_by: [-0.1, 0]
    buttons: [0] # right pad, bottom button

  head_up:
    type: action
    action_name: /head_controller/increment
    action_goal:
      increment_by: [0.1, 0]
    buttons: [4] # right pad, top button

  head_left:
    type: action
    action_name: /head_controller/increment
    action_goal:
      increment_by: [0, 0.1]
    buttons: [2] # right pad, left button

  head_right:
    type: action
    action_name: /head_controller/increment
    action_goal:
      increment_by: [0, -0.1]
    buttons: [1] # right pad, right button

  close_gripper:
    type: action
    action_name: /gripper_controller/increment
    action_goal:
      increment_by: [-0.01]
    buttons: [5] # RB

  open_gripper:
    type: action
    action_name: /gripper_controller/increment
    action_goal:
      increment_by: [0.01]
    buttons: [5] # LB
